In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

# learning

In [106]:
a = np.array([1, 2, 3])


def somefunc(array):
    array[2] = 69
    array[0] = 3
    return array


def intfunc(intg: int) -> int:
    intg = intg - 69
    return intg


g = 10
k = intfunc(g)
print(g, k)
g = g - 3
print(g)
b = g
g += 6
print(b, g)

b = somefunc(a)
print(a, b)
j = np.array([i**2 for i in range(10)])
print(j)


def kwargf(*args, **kwargs) -> None:
    print(args, kwargs)
    print(args, *kwargs)
    # print(args, **kwargs)  # this ain't valid


kwargf(1, 2, "bullet", x=3, y=69, z="asdf", kewa="kasdf")

10 -59
7
7 13
[ 3  2 69] [ 3  2 69]
[ 0  1  4  9 16 25 36 49 64 81]
(1, 2, 'bullet') {'x': 3, 'y': 69, 'z': 'asdf', 'kewa': 'kasdf'}
(1, 2, 'bullet') x y z kewa


TypeError: 'x' is an invalid keyword argument for print()

In [92]:
from dataclasses import dataclass, fields


@dataclass(init=False)
class Point:
    x: int
    y: int

    def __init__(self, var1, var2):
        self.var1: int = var1
        self.var2 = var2


point_fields = fields(Point)
for field in point_fields:
    print(f"Field Name: {field.name}")
    print(f"Field Type: {field.type}")
    print(f"Default Value: {field.default}")
    # print(f"Is Field Optional: {field.default_factory is fields.MISSING}")
    print("---")

Field Name: x
Field Type: <class 'int'>
Default Value: <dataclasses._MISSING_TYPE object at 0x000001FBE0CA6310>
---
Field Name: y
Field Type: <class 'int'>
Default Value: <dataclasses._MISSING_TYPE object at 0x000001FBE0CA6310>
---


In [74]:
def appcommand():  # another way of making decorators. So basically, appcomand doesn't accept the function itself, you have to call it so that it returns the decorator function object which can be called
    def decorator(
        f,
    ):  # to accept the function being decorated. When using it, need to call it by writing appcommand() (not appcomand WITHOUT the brakcets)
        print("what? ")
        print("f", f)
        # f()
        return f

    return decorator


@appcommand()  # what ????
def func11(
    *args,
) -> (
    None
):  # this function first goes through the decorator. After that, it is returned, which is when it gets called
    print("func11", *args)


p = func11(1, 2)
# p(1, 2)
print("p", p)
print("-----------------")
x = appcommand()  # calling a function which RETURNS another decorator function. Thus, calling x() will call the inner decorator function
print(x)

def func12(*args) -> None:
    print("func12", *args)


u = x(func12)  # returns a function into u
u(3)
print("u", u)
print("-----------------")
q = x(func12(1))  # func12() gets called first and then passed into the decorator
print("q", q)

what? 
f <function func11 at 0x000001AB484722A0>
func11 1 2
p None
-----------------
<function appcommand.<locals>.decorator at 0x000001AB48473B00>
what? 
f <function func12 at 0x000001AB48472CA0>
func12 3
u <function func12 at 0x000001AB48472CA0>
-----------------
func12 1
what? 
f None
q None


In [104]:
from typing import Callable, Any


def countdown(
    n,
):  # generator, returns a generator object which is an iterator that you can iterate over (e.g. using next())
    while (
        n > 0
    ):  # iterating over the generator, the function is paused at each yield, and the yielded value is returned
        yield n  # when you continue iterating, the function resumes execution from where it paused and continues
        n -= 1  # until the next yield statement, and so on...


# generators are made with the yield keyword
counter = countdown(5)

# an iterator is an object in python which has __next__ and __iter__ methods implemented, and it is used to iterate over iterables
# one at a time, w/o having to store all the elements in memory. Values are retreived and processed on the fly (as needed)

# Using next() to manually iterate through the generator
print(next(counter))  # Output: 5
print(next(counter))  # Output: 4
print(next(counter))  # Output: 3
print(next(counter))  # Output: 2
print(next(counter))  # Output: 1

print("!=========================================!")


def func(*args):
    print("in f args ", args)
    print("in f *args ", *args)
    for elem in args:
        print(elem)
    var = 69 + args[1] if args[1] < 0 else args[1]  # conditional expression
    return var


def decfunc(
    f: Callable,
) -> (
    Callable
):  # accepts a function and return a function (functions are objects in python). Notice the type hinting
    """decorator function"""

    def wrappername(
        *args,
    ) -> (
        Any
    ):  # nested wrapper function which wraps around our input function to modify the execution of the function w/o having to modify the input function itself
        print("start")
        print("pre f args ", args)
        print("pre f *args ", *args)
        print("f input is (args, *args)")
        rv = f(
            args, *args
        )  # so basically, you should pass in *args ONLY, because when you call the function you use brackets (), meaning you implicitly pass in a tuple, hence you should
        print(
            "end"
        )  # pass in *args because that will unpack the tuple into a tuple, thus leaving you with a tuple. If you pass in args, you will ultimately pass in a tuple within a tuple
        print(
            "rv ", rv
        )  # I pass in the result of calling f into a variable named 'rv', which is then the return value of the wrappername function
        return rv

    return wrappername  # return a function, don't call it, i.e. don't return wrappername() because you want to return the wrappername function itself (functions are objects)


x = decfunc(
    func
)  # pass in the function WITHOUT any arguments because you don't wanna execute it, you just want to pass in the function itself
print(
    "x ", x
)  # The modified function is stored inside x, which you call via x(). x stores the wrappername function defined within decfunc
y = x(1, 2, 3)  # now you call/execute the function but it's now modified.
print(y)

print("!!========================================!!")


@decfunc

# a=3  # whatever is below the decorator, no matter how many spaces, will be decorated. So, a=3 will cause an error, cuz it's not a function being decorated


def func1(*args):
    print("in f args ", args)
    print("in f *args ", *args)
    for elem in args:
        print(elem)
    var = 69 + args[1] if args[1] < 0 else args[1]
    return var


def func69(
    *args,
) -> (
    None
):  # the decorator doesn't affect this, meaning it only affects the function below it
    print("func69")


print(func1(-5, 2))
func69()

print("!!!=======================================!!!")

func(1, 2, 3, 69)

sometup = (1, "a", 3)
print(*sometup, sometup)


# var1, var2, var3 = *sometup  # this is illegal syntax, it's applicable only inside of functions, where the star unpacks it into a single tuple
class SomeClass:
    def __init__(self, var):
        self.var = var

    def met(
        self,
    ) -> (
        None
    ):  # passing in the self here is crucial, without it callin SomeClass().met() will return an error
        print("asfd")


print("1", decfunc)
print("2", SomeClass)
print("3", SomeClass(_))
print("4", SomeClass.met)
print("5", SomeClass(_).met)
print("6", SomeClass(_).met())
classinst = SomeClass(_)
# classinst()  # this is invalid syntax because it is not callable.

5
4
3
2
1
!=========================================!
x  <function decfunc.<locals>.wrappername at 0x000001FBE3E858A0>
start
pre f args  (1, 2, 3)
pre f *args  1 2 3
f input is (args, *args)
in f args  ((1, 2, 3), 1, 2, 3)
in f *args  (1, 2, 3) 1 2 3
(1, 2, 3)
1
2
3
end
rv  1
1
!!========================================!!
start
pre f args  (-5, 2)
pre f *args  -5 2
f input is (args, *args)
in f args  ((-5, 2), -5, 2)
in f *args  (-5, 2) -5 2
(-5, 2)
-5
2
end
rv  64
64
func69
!!!=======================================!!!
in f args  (1, 2, 3, 69)
in f *args  1 2 3 69
1
2
3
69
1 a 3 (1, 'a', 3)
1 <function decfunc at 0x000001FBE4B58360>
2 <class '__main__.SomeClass'>
3 <__main__.SomeClass object at 0x000001FBED315050>
4 <function SomeClass.met at 0x000001FBED2CE5C0>
5 <bound method SomeClass.met of <__main__.SomeClass object at 0x000001FBED314F90>>
asfd
6 None


In [2]:
somelist = [
    i**2 for i in range(10)
]  # list comprehension; expression for member in iterable
print(somelist)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [3]:
for _ in range(5):
    print(_ - 1)

sometup = ("a", (4, "b"), "c")
tup1, (tup2, tup3), tup4 = sometup
tup1, tupa, tup4 = sometup
print(sometup)
print(tup1, tup2, tup3, tup4)
print(tup1, tupa, tup4)

-1
0
1
2
3
('a', (4, 'b'), 'c')
a 4 b c
a (4, 'b') c


In [4]:
# assert, type hinting, for _ in range(number), ..., understand and research. PEP 8 formatter
# In the original paper each head should have seperate weights, but in your code all heads share the same weights. here are two steps to fix it:
# 1. in __init__:  self.queries = nn.Linear(self.embed_size, self.embed_size, bias=False) (same for key and value weights)
# 2. in forward: put "queries = self.queries(queries)" above "queries = queries.reshape(...)" (also same for keys and values)

In [15]:
# reshape play around. Internship (TUI + transformers + study QM + syllabi and dates + research do)
tensorplay = torch.tensor([[[1, 2], [4, 3], [5, 6]], [[9, 10], [0, -1], [69, 34]]])
print(tensorplay, tensorplay.shape)
tensorplay1 = tensorplay.reshape(3, 2, -1)
print(tensorplay1, tensorplay1.shape)
tensorplay1 = tensorplay.reshape([4, 1, -1])
print(tensorplay1, tensorplay1.shape)
tensorplay2 = torch.flatten(tensorplay)
print(tensorplay2, tensorplay2.shape)
tensorplay2 = tensorplay.reshape(-1)
print(tensorplay2, tensorplay2.shape)
tensorplay3 = tensorplay.reshape(6, 2)
print(tensorplay3, tensorplay3.shape)
tensorplay5 = tensorplay3.reshape(12)
print(tensorplay5, tensorplay5.shape)
tensorplay4 = torch.transpose(tensorplay, 1, 2)
print(tensorplay4, tensorplay4.shape)
print(tensorplay5[3:], tensorplay5[:3])

tensor([[[ 1,  2],
         [ 4,  3],
         [ 5,  6]],

        [[ 9, 10],
         [ 0, -1],
         [69, 34]]]) torch.Size([2, 3, 2])
tensor([[[ 1,  2],
         [ 4,  3]],

        [[ 5,  6],
         [ 9, 10]],

        [[ 0, -1],
         [69, 34]]]) torch.Size([3, 2, 2])
tensor([[[ 1,  2,  4]],

        [[ 3,  5,  6]],

        [[ 9, 10,  0]],

        [[-1, 69, 34]]]) torch.Size([4, 1, 3])
tensor([ 1,  2,  4,  3,  5,  6,  9, 10,  0, -1, 69, 34]) torch.Size([12])
tensor([ 1,  2,  4,  3,  5,  6,  9, 10,  0, -1, 69, 34]) torch.Size([12])
tensor([[ 1,  2],
        [ 4,  3],
        [ 5,  6],
        [ 9, 10],
        [ 0, -1],
        [69, 34]]) torch.Size([6, 2])
tensor([ 1,  2,  4,  3,  5,  6,  9, 10,  0, -1, 69, 34]) torch.Size([12])
tensor([[[ 1,  4,  5],
         [ 2,  3,  6]],

        [[ 9,  0, 69],
         [10, -1, 34]]]) torch.Size([2, 2, 3])
tensor([ 3,  5,  6,  9, 10,  0, -1, 69, 34]) tensor([1, 2, 4])


In [6]:
layer = nn.Linear(20, 100)
input = torch.randn(4, 6, 20)
output = layer(input)
print(input.shape)
print(output.shape)
# linear is pretty cool
sometens = torch.randn(2, 4, 12, 40)
permtens = torch.permute(sometens, (0, 2, 1, 3))
print(sometens.shape)
print(permtens.shape)
print(torch.tensor([[1, 2, 3, 4, 69], [0, 5, 4, 16, 36]]) ** (1 / 2))

torch.Size([4, 6, 20])
torch.Size([4, 6, 100])
torch.Size([2, 4, 12, 40])
torch.Size([2, 12, 4, 40])
tensor([[1.0000, 1.4142, 1.7321, 2.0000, 8.3066],
        [0.0000, 2.2361, 2.0000, 4.0000, 6.0000]])


In [7]:
xein = torch.randn(4, 5)
yein = torch.einsum("ij, kj -> ik", xein, xein)  # xx^T
yein2 = torch.mm(xein, torch.transpose(xein, 0, 1))
print(yein)
print(yein2)
yein = torch.einsum("ij, ik -> jk", xein, xein)  # x^Tx
yein2 = torch.mm(torch.transpose(xein, 0, 1), xein)
print(yein)
print(yein2)
# so, essentially label the dimensions with indices and only repeat those that want to sum over and that are of equal length in that dimension. Others should be different,
# even if their length is the same (like in the above examples), cuz you're not summing over them. Also, if want to sum, that index should not be in the output
bein1 = torch.randn(2, 6, 5)
bein2 = torch.randn(2, 5, 6)
oein1 = torch.einsum("bij, bjk -> bik", bein1, bein2)
oein2 = torch.bmm(bein1, bein2)
print("ein", oein1, oein1.shape)
print("bmm", oein2, oein2.shape)

tensor([[ 5.5912, -0.9753, -4.6705,  1.2506],
        [-0.9753,  6.2566, -3.0563, -2.1195],
        [-4.6705, -3.0563,  9.5055, -2.8523],
        [ 1.2506, -2.1195, -2.8523,  4.1146]])
tensor([[ 5.5912, -0.9753, -4.6705,  1.2506],
        [-0.9753,  6.2566, -3.0563, -2.1195],
        [-4.6705, -3.0563,  9.5055, -2.8523],
        [ 1.2506, -2.1195, -2.8523,  4.1146]])
tensor([[ 5.9048, -2.4460,  0.6294, -0.5834,  0.6248],
        [-2.4460,  5.3137, -0.3901, -0.2312,  1.6926],
        [ 0.6294, -0.3901,  0.2663,  0.8730, -0.6148],
        [-0.5834, -0.2312,  0.8730,  8.9054, -6.3002],
        [ 0.6248,  1.6926, -0.6148, -6.3002,  5.0777]])
tensor([[ 5.9048, -2.4460,  0.6294, -0.5834,  0.6248],
        [-2.4460,  5.3137, -0.3901, -0.2312,  1.6926],
        [ 0.6294, -0.3901,  0.2663,  0.8730, -0.6148],
        [-0.5834, -0.2312,  0.8730,  8.9054, -6.3002],
        [ 0.6248,  1.6926, -0.6148, -6.3002,  5.0777]])
ein tensor([[[ 0.6642,  1.3091,  0.4851,  1.6559, -0.6190,  0.7024],
         

In [8]:
sinput = torch.randn(3, 4)

In [9]:
print(torch.softmax(sinput, dim=0))
print(torch.softmax(sinput, dim=1))
print(
    torch.sum(torch.softmax(sinput, dim=0)[:, 0]),
    torch.sum(torch.softmax(sinput, dim=0)[:, 1]),
    torch.sum(torch.softmax(sinput, dim=0)[:, 2]),
    torch.sum(torch.softmax(sinput, dim=0)[:, 3]),
)
print(
    torch.sum(torch.softmax(sinput, dim=1)[0, :]),
    torch.sum(torch.softmax(sinput, dim=1)[1, :]),
    torch.sum(torch.softmax(sinput, dim=1)[2, :]),
)

tensor([[0.2066, 0.0779, 0.4895, 0.0879],
        [0.4484, 0.0473, 0.1096, 0.0220],
        [0.3450, 0.8748, 0.4010, 0.8900]])
tensor([[0.2858, 0.1480, 0.2354, 0.3308],
        [0.7335, 0.1062, 0.0623, 0.0980],
        [0.0840, 0.2926, 0.0340, 0.5894]])
tensor(1.) tensor(1.) tensor(1.) tensor(1.)
tensor(1.) tensor(1.) tensor(1.)


In [34]:
# test if torch tensors are modified inside functions 
class TestClass: 
    def __init__(self, a, b): 
        print('AA', a) 
        self.a = a 
        self.b = b 
    def display(self):
        print(self.a, self.b)
        
TestClass(1, 2).display()

def torchfunc(tensor: torch.Tensor) -> torch.Tensor: 
    dropout = nn.Dropout(p=0.5)
    dropped = dropout(tensor)
    tensor = tensor + 69
    return dropped , tensor

testtens = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7], dtype=torch.float32)
print(testtens)
droppedtens, testtens2 = torchfunc(testtens)
print(testtens)
print(testtens2)
print(droppedtens)

AA 1
1 2
tensor([0., 1., 2., 3., 4., 5., 6., 7.])
tensor([0., 1., 2., 3., 4., 5., 6., 7.])
tensor([69., 70., 71., 72., 73., 74., 75., 76.])
tensor([ 0.,  2.,  0.,  0.,  0., 10., 12.,  0.])


# transformer

In [76]:
class SelfAttention(nn.Module):
    def __init__(self, embed_dim: int, n_heads: int):
        super().__init__()
        self.embed_dim = embed_dim
        self.n_heads = n_heads
        self.head_dim = embed_dim // n_heads

        assert (
            self.head_dim * n_heads == embed_dim
        ), "embed_dim needs to be divisible by n_heads"

        self.queries = nn.Linear(self.embed_dim, self.embed_dim, bias=False)
        self.keys = nn.Linear(self.embed_dim, self.embed_dim, bias=False)
        self.values = nn.Linear(self.embed_dim, self.embed_dim, bias=False)
        self.fc_out = nn.Linear(self.embed_dim, self.embed_dim)

    def forward(
        self,
        pre_queries: torch.Tensor,
        pre_keys: torch.Tensor,
        pre_values: torch.Tensor,
        mask: torch.Tensor,
    ) -> torch.Tensor:  # shape of pre_query, pre_key, pre_value are [N, seq_len, embed_dim]. It has the 'pre' prefix because they're the inputs (word vectors) to get the queries, keys, and values
        N = pre_queries.shape[0]  # batch size
        queries_seq_len, keys_seq_len, values_seq_len = pre_queries.shape[1], pre_keys.shape[1], pre_values.shape[1]  # sequence (sentence) lengths which may be different in encoder/decoder
        # splitting into n_heads pieces for multihead attention

        queries = self.queries(pre_queries)
        keys = self.keys(pre_keys)
        values = self.values(pre_values)

        queries = queries.reshape(N, queries_seq_len, self.n_heads, self.head_dim)
        keys = keys.reshape(N, keys_seq_len, self.n_heads, self.head_dim)
        values = values.reshape(N, values_seq_len, self.n_heads, self.head_dim)

        attention_grid = torch.einsum("nqhd, nkhd -> nhqk", queries, keys)  # shape is [N, self.n_heads, queries_seq_len, keys_seq_len], we sum over self.head_dim
        # you basically get the attention grid for every word in the sequence but with different attentions for every part/head of the subdivided word embeddings (self.head_dim = embed_dim // n_heads)

        if mask is not None:
            attention_grid = attention_grid.masked_fill(mask == 0, float("-1e20"))

        attention_weights = torch.softmax(attention_grid / self.head_dim ** (1 / 2), dim=3)  # dim=3 because they need to sum up to one along the key dimension (cuz query asks keys intuitively)

        multi_head = torch.einsum("nhql, nlhd -> nqhd", attention_weights, values)  # this computes all the heads which now need to be concatenated. Shape is [N, query_seq_len, self.n_heads, self.head_dim]
        # you sum over the keys and values dimensions because that's how the math works out
        # sum_i array[w_{1,i}*v_{i,1} ... w_{1,i}*v_{i,self.embed_dim}], hence sum over the key dimension (which is equal in length to keys_seq_len) and the values_seq_len dimension
        # i.e., you do a linear combination of the values (word vectors) weighted by the attention_weights to FINALLY get your attention vector for the corresponding query vector
        multi_head_attention = multi_head.reshape(N, queries_seq_len, self.embed_dim)  # concatenation, notice that it's the attention vectors for each corresponding query
        multi_head_attention = self.fc_out(multi_head_attention)  # final weight matrix multiplication

        return multi_head_attention  # shape is [N, queries_seq_len, embed_dim], i.e. the attention vector for each corresponding query vector


class TransformerBlock(nn.Module):
    def __init__(
        self, embed_dim: int, n_heads: int, dropout: float, forward_expansion: int
    ):
        super().__init__()
        self.attention = SelfAttention(embed_dim, n_heads)
        self.norm = nn.LayerNorm(embed_dim)
        self.linear_1 = nn.Linear(embed_dim, forward_expansion * embed_dim)
        self.linear_2 = nn.Linear(forward_expansion * embed_dim, embed_dim)
        self.dropout = nn.Dropout(p=dropout)

    def forward(
        self,
        pre_queries: torch.Tensor,
        pre_keys: torch.Tensor,
        pre_values: torch.Tensor,
        mask: torch.Tensor,
    ) -> torch.Tensor:
        attention = self.attention(pre_queries, pre_keys, pre_values, mask)
        x = self.dropout(self.norm(attention + pre_queries))  # initially, the pre_queries, pre_keys, pre_values are either the same or different if in the decoder, they're just the word vectors
        x_fc = self.linear_2(F.gelu(self.linear_1(x)))
        out = self.dropout(self.norm(x + x_fc))
        return out


class Encoder(nn.Module):
    def __init__(
        self,
        src_vocab_size: int,
        embed_dim: int,
        n_layers: int,
        n_heads: int,
        device: torch.device,
        forward_expansion: int,
        dropout: float,
        max_seq_length: int,
    ):
        super().__init__()
        self.device = device
        self.word_embedding = nn.Embedding(src_vocab_size, embed_dim)
        self.positional_embedding = nn.Embedding(max_seq_length, embed_dim)
        self.layers = nn.ModuleList(
            [
                TransformerBlock(embed_dim, n_heads, dropout, forward_expansion)
                for _ in range(n_layers)
            ]
        )
        self.dropout = nn.Dropout(p=dropout)

    def forward(self, x: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        N, seq_length = x.shape  # x is the input tensor which contains the sentences and words, i.e. its shape is N x seq_length, where N = batch size and seq_length = sentence size (note: seq_length = max_seq_length)
        positions = torch.arange(0, seq_length).expand(N, -1).to(self.device)
        out = self.dropout(self.word_embedding(x) + self.positional_embedding(positions))  # these are the word vectors
        for layer in self.layers:
            out = layer(out, out, out, mask)  # calling the forward method of the TransformerBlock
        return out


class DecoderBlock(nn.Module):
    def __init__(
        self,
        embed_dim: int,
        n_heads: int,
        forward_expansion: int,
        dropout: float,
        device: torch.device,
    ):
        super().__init__()
        self.norm = nn.LayerNorm(embed_dim)
        self.attention = SelfAttention(embed_dim, n_heads)
        self.transformer_block = TransformerBlock(embed_dim, n_heads, dropout, forward_expansion)
        self.device = device
        self.dropout = nn.Dropout(p=dropout)

    def forward(
        self,
        x: torch.Tensor,
        keys: torch.Tensor,
        values: torch.Tensor,
        src_mask: torch.Tensor,
        trg_mask: torch.Tensor,
    ) -> torch.Tensor:  # src_mask is optional, it's so that we don't do computations on padded values. trg_mask is not optional, you MUST have it
        attention = self.attention(x, x, x, trg_mask)
        queries = self.dropout(self.norm(x + attention))  # the queries in the decoder which get passed into the second multiheaded attention
        out = self.transformer_block(queries, keys, values, src_mask)
        return out


class Decoder(nn.Module):
    def __init__(
        self,
        trg_vocab_size: int,
        embed_dim: int,
        n_layers: int,
        n_heads: int,
        device: torch.device,
        forward_expansion: int,
        dropout: float,
        max_seq_length: int,
    ):
        super().__init__()
        self.device = device
        self.word_embedding = nn.Embedding(trg_vocab_size, embed_dim)
        self.positional_embedding = nn.Embedding(max_seq_length, embed_dim)
        self.layers = nn.ModuleList(
            [
                DecoderBlock(embed_dim, n_heads, forward_expansion, dropout, device)
                for _ in range(n_layers)
            ]
        )
        self.fc_out = nn.Linear(embed_dim, trg_vocab_size)
        self.dropout = nn.Dropout(p=dropout)

    def forward(
        self,
        x: torch.Tensor,
        encoder_out: torch.Tensor,
        src_mask: torch.Tensor,
        trg_mask: torch.Tensor,
    ) -> torch.Tensor:
        N, seq_length = x.shape
        positions = torch.arange(0, seq_length).expand(N, -1).to(self.device)
        x = self.dropout(self.word_embedding(x) + self.positional_embedding(positions))
        for layer in self.layers:
            x = layer(x, encoder_out, encoder_out, src_mask, trg_mask)  # encoder output is the attention vector which went through the feedforward nets & normalization + skip connection
        out = torch.softmax(self.fc_out(x), dim=1)  # shape is [N, trg_vocab_size]
        return out


# think about how everything works and the dimensionality and the masks, make sure to understand everything and how encoding (tokenization) work with word embeddings and everything else (attention)
# think about the vocab sizes and the masks (why should only the DECODER be masked?). Undertand the MASKS and vocabs and MAX_SEQ_LENGTH

# tmrw: transformer code finish & TUI 8 pm + set research code running and do the research tasks + D3 and calcium figure out and start skincare + research formulae 

# UNDERSTAND THE PROBABILITY DISTROS IN NLP (LEARNING TASK, see the papers)
# find a dataset for translation (in kaggle, huggingface)

In [ ]:
class ChatGPT(nn.Module): 
    def __init__(self, src_voab_size:int, trg_vocab_size: int, embed_dim: int, n_layers: int, n_heads: int, device: torch.device, forward_expansion: int, dropout: float, max_seq_length: int): 
        super().__init__()
        
        self.dropout = nn.Dropout(p=dropout)
        
        
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        pass 


class Translator(nn.Module):   
    def __init__(
        self, 
        src_vocab_size: int, 
        trg_vocab_size: int, 
        src_pad_idx: int, 
        trg_pad_idx: int, 
        embed_dim: int, 
        n_layers: int, 
        n_heads: int, 
        device: torch.device, 
        forward_expansion: int, 
        dropout: float, 
        max_seq_length: int
    ):
        super().__init__() 
        
        self.encoder = Encoder(
            src_vocab_size, 
            embed_dim, 
            n_layers, 
            n_heads, 
            device, 
            forward_expansion, 
            dropout, 
            max_seq_length
        )
        
        self.decoder = Decoder(
            trg_vocab_size, 
            embed_dim, 
            n_layers, 
            n_heads, 
            device, 
            forward_expansion, 
            dropout, 
            max_seq_length
        )
        
        self.src_pad_idx = src_pad_idx
        self.trg_pad_idx = trg_pad_idx
        self.device = device 
        
    def make_src_mask(self, src) -> torch.Tensor:  # src is of shape [N, src sentence length]
        src_mask = (src != self.src_pad_idx).unsqueeze(1).unsqueeze(2)  # understand this. Shape is [N, 1, 1, src sentece length], makes this broadcastable 
        return src_mask.to(self.device)
    
    def make_trg_mask(self, trg) -> torch.Tensor:
        N, trg_length = trg.shape
        trg_mask = torch.tril(torch.ones(trg_length, trg_length)).expand(N, 1, trg_length, trg_length) 
        return trg_mask.to(self.device)
              
    def forward(
        self, 
        src: torch.Tensor,  # WHAT EXACTLY IS SRC AND TRG? The source and target sentences i suppose 
        trg: torch.Tensor,
    ) -> torch.Tensor:
        src_mask = self.make_src_mask(src)
        trg_mask = self.make_src_mask(trg)
        encoder_src = self.encoder(src, src_mask)
        out = self.decoder(trg, encoder_src, src_mask, trg_mask)
        return out 
    
    # understand how it all ties together 

In [30]:
a = torch.tensor([[1, 2], [3, 4]])
e = 2
f = (a == e)
print('a', a, a.shape) 
b = a.unsqueeze(0)
print('b', b, b.shape, '\n', b[0, :, :])
c = a.unsqueeze(1)
print('c', c, c.shape, '\n', c[:, 0, :])
d = a.unsqueeze(2)  # range of possible unsqueeze argument values is [-3, 2]
print('d', d, d.shape, '\n', d[:, :, 0])
print(f, '\n', f == 0)

a tensor([[1, 2],
        [3, 4]]) torch.Size([2, 2])
b tensor([[[1, 2],
         [3, 4]]]) torch.Size([1, 2, 2]) 
 tensor([[1, 2],
        [3, 4]])
c tensor([[[1, 2]],

        [[3, 4]]]) torch.Size([2, 1, 2]) 
 tensor([[1, 2],
        [3, 4]])
d tensor([[[1],
         [2]],

        [[3],
         [4]]]) torch.Size([2, 2, 1]) 
 tensor([[1, 2],
        [3, 4]])
tensor([[False,  True],
        [False, False]]) 
 tensor([[ True, False],
        [ True,  True]])


In [4]:
m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)
print(input)
print(output)
asd = torch.randn(4, 4)
print(torch.tril(asd))

tensor([[-0.3459,  1.6685, -0.0150],
        [ 1.4803,  0.5445,  0.0353]])
tensor([[0.1011, 0.7581, 0.1408],
        [0.6142, 0.2410, 0.1448]])
tensor([[-1.2558,  0.0000,  0.0000,  0.0000],
        [-1.0626, -0.8592,  0.0000,  0.0000],
        [-0.5719,  0.2874, -0.0259,  0.0000],
        [-0.0635, -0.4276,  1.0535, -0.2341]])


In [56]:
emb = nn.Embedding(10, 4)  
print(emb)
emb.weight

Embedding(10, 4)


Parameter containing:
tensor([[-1.2097e-01, -6.5288e-01,  5.8031e-03, -1.5795e+00],
        [-1.7667e+00, -1.4778e-03,  3.7534e-01,  4.3692e-01],
        [-1.4814e+00, -5.5933e-01, -1.0190e-01,  6.0000e-01],
        [-7.3397e-01,  2.3712e-01,  6.7632e-01, -3.9567e-01],
        [-1.6704e+00, -1.3662e-01,  8.7118e-01,  7.5154e-01],
        [ 2.6692e-01, -8.9575e-01, -2.0876e-02, -1.2119e+00],
        [-1.3995e-02, -4.0364e-01, -7.1366e-01,  1.3797e+00],
        [ 7.8857e-02,  8.3519e-01,  4.6091e-01, -1.3989e+00],
        [-1.0316e+00, -1.3021e+00, -1.7873e+00, -3.0839e-01],
        [-6.5690e-01,  1.5618e+00, -4.4255e-02,  1.3002e+00]],
       requires_grad=True)

In [61]:
tens = torch.tensor([[2, 3], [5, 5]])  # represents tokenized sentences with a batch size of 2 
print(tens, tens.shape)
embedded = emb(tens) 
print(embedded, embedded.shape)

tensor([[2, 3],
        [5, 5]]) torch.Size([2, 2])
tensor([[[-1.4814, -0.5593, -0.1019,  0.6000],
         [-0.7340,  0.2371,  0.6763, -0.3957]],

        [[ 0.2669, -0.8958, -0.0209, -1.2119],
         [ 0.2669, -0.8958, -0.0209, -1.2119]]], grad_fn=<EmbeddingBackward0>) torch.Size([2, 2, 4])


In [63]:
layers = nn.ModuleList(
            [TransformerBlock(5, 5, 1/10, 3) for _ in range(2)]
        )
print(layers, len(layers))
for _ in range(5):
    print('exec')

ModuleList(
  (0-1): 2 x TransformerBlock(
    (attention): SelfAttention(
      (queries): Linear(in_features=5, out_features=5, bias=False)
      (keys): Linear(in_features=5, out_features=5, bias=False)
      (values): Linear(in_features=5, out_features=5, bias=False)
      (fc_out): Linear(in_features=5, out_features=5, bias=True)
    )
    (norm): LayerNorm((5,), eps=1e-05, elementwise_affine=True)
    (linear_1): Linear(in_features=5, out_features=15, bias=True)
    (linear_2): Linear(in_features=15, out_features=5, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
) 2
exec
exec
exec
exec
exec


In [54]:
arr = torch.arange(-3, 5)
print(arr, arr.shape)
arr1 = arr.expand(3, 8)
print(arr1, arr1.shape)
arr2 = arr.expand(3, -1)
print(arr2, arr2.shape)
arr3 = arr.expand(5, 2, -1)
print(arr3, arr3.shape)
arr = torch.randn(3, 3)
print(arr, arr.shape)
arr4 = arr.expand(5, 1, 3, 3)
print(arr4, arr4.shape)

tensor([-3, -2, -1,  0,  1,  2,  3,  4]) torch.Size([8])
tensor([[-3, -2, -1,  0,  1,  2,  3,  4],
        [-3, -2, -1,  0,  1,  2,  3,  4],
        [-3, -2, -1,  0,  1,  2,  3,  4]]) torch.Size([3, 8])
tensor([[-3, -2, -1,  0,  1,  2,  3,  4],
        [-3, -2, -1,  0,  1,  2,  3,  4],
        [-3, -2, -1,  0,  1,  2,  3,  4]]) torch.Size([3, 8])
tensor([[[-3, -2, -1,  0,  1,  2,  3,  4],
         [-3, -2, -1,  0,  1,  2,  3,  4]],

        [[-3, -2, -1,  0,  1,  2,  3,  4],
         [-3, -2, -1,  0,  1,  2,  3,  4]],

        [[-3, -2, -1,  0,  1,  2,  3,  4],
         [-3, -2, -1,  0,  1,  2,  3,  4]],

        [[-3, -2, -1,  0,  1,  2,  3,  4],
         [-3, -2, -1,  0,  1,  2,  3,  4]],

        [[-3, -2, -1,  0,  1,  2,  3,  4],
         [-3, -2, -1,  0,  1,  2,  3,  4]]]) torch.Size([5, 2, 8])
tensor([[-0.5650,  0.8798,  0.0707],
        [ 2.7031,  0.0204, -0.7219],
        [-0.9288, -0.5120,  0.6686]]) torch.Size([3, 3])
tensor([[[[-0.5650,  0.8798,  0.0707],
          [ 2.7031,

In [47]:
num_set = {}
print(3 in num_set, len(num_set))
print(5.9 // 2, 5.9 % 2, 3 // 2, 10 // 5, 10 // 3)

False 0
2.0 1.9000000000000004 1 2 3
